[project]
name = "trueformawg"
version = "0.1.0"
description = " A class to control a TrueFrom arbitrary waveform generator via Python through VISA commands."
authors = [
    {name = "Federico Scarpioni", email = "federicoscarpioni@gmail.com"},
]
maintainers = [
    {name = "Federico Scarpioni", email = "federicoscarpioni@gmail.com"},
]
readme = "README.md"
requires-python = ""
dependencies = [,
    "numpy",
    "pyvisa"
]
license = "MIT"
license-files = ["LICENSE"]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
Repository = "https://github.com/federicoscarpioni/trueformawg.git"
Issues = "https://github.com/federicoscarpioni/trueformawg/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["B", "E", "F", "S", "UP"]